### PR TITLE
Type check scalar expressions

### PR DESCRIPTION
**Pull request by petermattis**
This change is [Reviewable](https://reviewable.io/reviews/petermattis/opttoy/44)

### CODE REVIEW

**Comment by petermattis** [comment]
Figured out that cockroach currently handles `tree.Subquery` but replacing it with a `subquery` node. The same approach can be taken in `opttoy`.

**Comment by petermattis** [comment]
@knz Please take a look at this. I've been wondering how exactly we were going to integrate type checking with building of the `expr` tree. My previous understanding was that type checking and name resolution would somehow occur before the `expr` tree was built. That is, a fully resolved and typed AST would be used to build the `expr` tree. But, achieving this seems like a large bit of refactoring as name resolution and typing is currently done during `planNode` construction. This PR takes the approach of building the `expr` tree from a raw AST and calls into the existing `tree.TypeCheck` code to type check scalar expressions as they are found.

**Comment by knz** [comment]
I believe the approach is correct but I do not find any occurrence of `TypeCheck` in this PR. Where is it called?

---

Reviewed 11 of 19 files at r1.
Review status: 11 of 19 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/petermattis/opttoy/44#-:-L0e1tIzjjGvL62T3-qr:b-mw7ur7)*

**Comment by petermattis** [comment]
Review status: 11 of 19 files reviewed at latest revision, 1 unresolved discussion.

---

*[v3/scope.go, line 27 at r1](https://reviewable.io:443/reviews/petermattis/opttoy/44#-L0e3TJ5aM8nXdJeGLp_:-L0e3TJ5aM8nXdJeGLpa:b-eojw37) ([raw file](https://github.com/petermattis/opttoy/blob/a275bd302ad52c083eb11f0f3ccbff19c6dd4383/v3/scope.go#L27)):*
> ```Go
> func (s *scope) resolve(expr tree.Expr, desired types.T) tree.TypedExpr {
> 	expr, _ = tree.WalkExpr(s, expr)
> 	texpr, err := tree.TypeCheck(expr, &s.state.semaCtx, desired)
> ```

@knz here!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/petermattis/opttoy/44)*

**Comment by knz** [comment]
Ok, I don't dislike this. 

---

Review status: 11 of 19 files reviewed at latest revision, 3 unresolved discussions.

---

*[v3/scope.go, line 27 at r1](https://reviewable.io:443/reviews/petermattis/opttoy/44#-L0e3TJ5aM8nXdJeGLp_:-L0e44T1SxKJHEBdM27n:b9lr8iv) ([raw file](https://github.com/petermattis/opttoy/blob/a275bd302ad52c083eb11f0f3ccbff19c6dd4383/v3/scope.go#L27)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

@knz here!
</blockquote></details>

Damn reviewable was simply not showing this file... :crying_cat_face: 

Anyway ok, but errors will need to be propagated.

---

*[v3/scope.go, line 44 at r1](https://reviewable.io:443/reviews/petermattis/opttoy/44#-L0e4yIMulVnywVNxeQd:-L0e4yIN2emnZRe1c9ya:b-s6lbl) ([raw file](https://github.com/petermattis/opttoy/blob/a275bd302ad52c083eb11f0f3ccbff19c6dd4383/v3/scope.go#L44)):*
> ```Go
> }
> 
> // NB: This code is adapted from sql/select_name_resolution.go.
> ```

This will also need to be double-checked when adapted into CockroachDB. 

---

*[v3/scope.go, line 175 at r1](https://reviewable.io:443/reviews/petermattis/opttoy/44#-L0e4i4srAYF1_KeiwuP:-L0e4i4srAYF1_KeiwuQ:b2abzrz) ([raw file](https://github.com/petermattis/opttoy/blob/a275bd302ad52c083eb11f0f3ccbff19c6dd4383/v3/scope.go#L175)):*
> ```Go
> func (s *subquery) TypeCheck(_ *tree.SemaContext, desired types.T) (tree.TypedExpr, error) {
> 	// TODO(peter): We're assuming the type of the subquery is the type of the
> 	// first column. This is all sorts of wrong.
> ```

We have a types.TTable suitable for subqueries.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/petermattis/opttoy/44#-:-L0e58NWW3KffHJYbEwS:b-ajs055)*

**Comment by petermattis** [comment]
Review status: 11 of 19 files reviewed at latest revision, 3 unresolved discussions.

---

*[v3/scope.go, line 27 at r1](https://reviewable.io:443/reviews/petermattis/opttoy/44#-L0e3TJ5aM8nXdJeGLp_:-L0gFa1UkuGDMCIUchWn:bh6133o) ([raw file](https://github.com/petermattis/opttoy/blob/a275bd302ad52c083eb11f0f3ccbff19c6dd4383/v3/scope.go#L27)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Damn reviewable was simply not showing this file... :crying_cat_face: 

Anyway ok, but errors will need to be propagated.
</blockquote></details>

I've had reviewable do that to me too!

Re errors: I basically don't propagate them anywhere in opttoy and instead panic. Certainly simplifies the code. Might be worth discussing if this is reasonable in code that doesn't use locks are mutate shared data structures. 

---

*[v3/scope.go, line 44 at r1](https://reviewable.io:443/reviews/petermattis/opttoy/44#-L0e4yIMulVnywVNxeQd:-L0gFtHwymjVoHW3zzOB:b-3glmgh) ([raw file](https://github.com/petermattis/opttoy/blob/a275bd302ad52c083eb11f0f3ccbff19c6dd4383/v3/scope.go#L44)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This will also need to be double-checked when adapted into CockroachDB. 
</blockquote></details>

Agreed. 

---

*[v3/scope.go, line 175 at r1](https://reviewable.io:443/reviews/petermattis/opttoy/44#-L0e4i4srAYF1_KeiwuP:-L0gFuoE8SHTASM1M8gs:b-s402he) ([raw file](https://github.com/petermattis/opttoy/blob/a275bd302ad52c083eb11f0f3ccbff19c6dd4383/v3/scope.go#L175)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

We have a types.TTable suitable for subqueries.
</blockquote></details>

We don't seem to be using this for subqueries in crdb. Instead there is a bit of a monstrosity with `getSubqueryContext` and `subqueryVisitor`. I feel ok describing that as a monstrosity given that I was the original author. Did you have thoughts about how TTable would be used here? I need to investigate further.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/petermattis/opttoy/44)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 10 of 19 files reviewed at latest revision, 3 unresolved discussions.

---

*[v3/scope.go, line 27 at r1](https://reviewable.io:443/reviews/petermattis/opttoy/44#-L0e3TJ5aM8nXdJeGLp_:-L0jhUQY9T9Pgpg8lP9X:b8tuvir) ([raw file](https://github.com/petermattis/opttoy/blob/a275bd302ad52c083eb11f0f3ccbff19c6dd4383/v3/scope.go#L27)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I've had reviewable do that to me too!

Re errors: I basically don't propagate them anywhere in opttoy and instead panic. Certainly simplifies the code. Might be worth discussing if this is reasonable in code that doesn't use locks are mutate shared data structures. 
</blockquote></details>

I think panic with a top-level recover is very reasonable for code that doesn't affect global state. It is e.g. used by go's JSON library when unmarshaling.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/petermattis/opttoy/44#-:-L0ji_21Tjuzhqvm6RJP:bnfp4nl)*

**Pull request merged**
