### PR TITLE
[DO NOT MERGE] Use vtuple for typing subqueries

### PR DESCRIPTION
**Pull request by petermattis**
This change is [Reviewable](https://reviewable.io/reviews/petermattis/opttoy/48)

### CODE REVIEW

**Comment by petermattis** [comment]
Cc @knz

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[v3/scope.go, line 240 at r1](https://reviewable.io:443/reviews/petermattis/opttoy/48#-L1P-axbArOll-XSO7b0:-L1P-axbArOll-XSO7b1:b-9atb48) ([raw file](https://github.com/petermattis/opttoy/blob/35c9f47556f20eecdf3c21c08b31fc133efbfdb4/v3/scope.go#L240)):*
> ```Go
> 
> 	if s.table {
> 		// The subquery is in a "table" context. For example:
> ```

I don't know if "table" is the right way to talk about this. Maybe "multi-value" context.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/petermattis/opttoy/48#-:-L1P-rgTxtDmegZeXtvF:bnfp4nl)*

**Comment by petermattis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[v3/scope.go, line 240 at r1](https://reviewable.io:443/reviews/petermattis/opttoy/48#-L1P-axbArOll-XSO7b0:-L1P4IZKxRyuduKN8x6N:b-b78qh6) ([raw file](https://github.com/petermattis/opttoy/blob/35c9f47556f20eecdf3c21c08b31fc133efbfdb4/v3/scope.go#L240)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I don't know if "table" is the right way to talk about this. Maybe "multi-value" context.
</blockquote></details>

How about `single-row` vs `multi-row`? `Multi-value` is slightly confusing, because `(SELECT (1, 2))` returns multiple values, but only a single row.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/petermattis/opttoy/48)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[v3/scope.go, line 214 at r1](https://reviewable.io:443/reviews/petermattis/opttoy/48#-L1PFUAOr-ZbIKaT5TTh:-L1PFUAOr-ZbIKaT5TTi:bmdlfkw) ([raw file](https://github.com/petermattis/opttoy/blob/35c9f47556f20eecdf3c21c08b31fc133efbfdb4/v3/scope.go#L214)):*
> ```Go
> 			//   SELECT 1 IN (SELECT 1)
> 			//
> 			// The type of the subquery will be "vtuple{int}". Now consider:
> ```

"consider the invalid query:" (it's hard to notice that this actually doesn't work if you're just skimming)

---

*[v3/scope.go, line 224 at r1](https://reviewable.io:443/reviews/petermattis/opttoy/48#-L1PG7zLg7mI8T_3XRRy:-L1PG7zLg7mI8T_3XRRz:btg8ggv) ([raw file](https://github.com/petermattis/opttoy/blob/35c9f47556f20eecdf3c21c08b31fc133efbfdb4/v3/scope.go#L224)):*
> ```Go
> 			//
> 			// Note that this query is semantically valid (the subquery has type
> 			// "vtuple{tuple{int,int}}"), while the previous query was not.
> ```

Can you add the examples `SELECT 1 IN (SELECT a FROM ab);` and `SELECT (1, 2) IN (SELECT a, b FROM ab)`? They're the same but it's more obvious why it needs to be a vtuple

---

*[v3/scope.go, line 240 at r1](https://reviewable.io:443/reviews/petermattis/opttoy/48#-L1P-axbArOll-XSO7b0:-L1PEadb7X9xGDn8SnQZ:b-1do5pt) ([raw file](https://github.com/petermattis/opttoy/blob/35c9f47556f20eecdf3c21c08b31fc133efbfdb4/v3/scope.go#L240)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

How about `single-row` vs `multi-row`? `Multi-value` is slightly confusing, because `(SELECT (1, 2))` returns multiple values, but only a single row.
</blockquote></details>

Arguably it returns a single value, the tuple `(1, 2)` (as shown by the invalid query `SELECT (1, 2) IN (SELECT (1, 2))`) 

`multi-row` and `table` are not much different.. I don't feel strongly about the naming.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/petermattis/opttoy/48)*

**Comment by petermattis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[v3/scope.go, line 214 at r1](https://reviewable.io:443/reviews/petermattis/opttoy/48#-L1PFUAOr-ZbIKaT5TTh:-L1QAVmfYEhIecad3KQT:b-tad4ku) ([raw file](https://github.com/petermattis/opttoy/blob/35c9f47556f20eecdf3c21c08b31fc133efbfdb4/v3/scope.go#L214)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

"consider the invalid query:" (it's hard to notice that this actually doesn't work if you're just skimming)
</blockquote></details>

I'm going to replace this with another PR, but ack nonetheless.

---

*[v3/scope.go, line 224 at r1](https://reviewable.io:443/reviews/petermattis/opttoy/48#-L1PG7zLg7mI8T_3XRRy:-L1QAY6R16Zi2diZ64Nc:bb6sh2i) ([raw file](https://github.com/petermattis/opttoy/blob/35c9f47556f20eecdf3c21c08b31fc133efbfdb4/v3/scope.go#L224)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Can you add the examples `SELECT 1 IN (SELECT a FROM ab);` and `SELECT (1, 2) IN (SELECT a, b FROM ab)`? They're the same but it's more obvious why it needs to be a vtuple
</blockquote></details>

Ack.

---

*[v3/scope.go, line 240 at r1](https://reviewable.io:443/reviews/petermattis/opttoy/48#-L1P-axbArOll-XSO7b0:-L1QAZHBmMfVX-IrPtIp:b-nenn52) ([raw file](https://github.com/petermattis/opttoy/blob/35c9f47556f20eecdf3c21c08b31fc133efbfdb4/v3/scope.go#L240)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Arguably it returns a single value, the tuple `(1, 2)` (as shown by the invalid query `SELECT (1, 2) IN (SELECT (1, 2))`) 

`multi-row` and `table` are not much different.. I don't feel strongly about the naming.
</blockquote></details>

Googling the nets, `multi-row` is the terminology I've seen most commonly used. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/petermattis/opttoy/48)*

**Pull request closed without merging**
