### PR TITLE
split bind into bind/advance

### PR DESCRIPTION
**Pull request by RaduBerinde**
This may be a bit more code overall, but I believe it's much more clear now.

---
This change is [Reviewable](https://reviewable.io/reviews/petermattis/opttoy/18)

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

Definitely seems cleaner to me. @rytaft you might want to take a look.

---

Review status: 0 of 2 files reviewed at latest revision, 6 unresolved discussions.

---

*[v3/memo.go, line 221 at r1](https://reviewable.io:443/reviews/petermattis/opttoy/18#-Kz1HRi2sCo5gdDpGbuZ:-Kz1HRi2sCo5gdDpGbu_:bid5qg5) ([raw file](https://github.com/petermattis/opttoy/blob/e2fff1ceedd5f3ecd6f81d2a61fb4ac41c637297/v3/memo.go#L221)):*
> ```Go
> }
> 
> func childPattern(pattern *expr, childIdx int) *expr {
> ```

This probably belongs in `pattern.go`.

---

*[v3/memo.go, line 251 at r1](https://reviewable.io:443/reviews/petermattis/opttoy/18#-Kz1H_EMHQNHtnR08cDf:-Kz1H_EMHQNHtnR08cDg:b-x8cvcx) ([raw file](https://github.com/petermattis/opttoy/blob/e2fff1ceedd5f3ecd6f81d2a61fb4ac41c637297/v3/memo.go#L251)):*
> ```Go
> 	}
> 
> 	cursor.children = make([]*expr, len(e.children))
> ```

I recall having to initialize `cursor.children` for `pattern leaf` at some point. Seems like that is no longer necessary if the tests are all still passing.

---

*[v3/memo.go, line 276 at r1](https://reviewable.io:443/reviews/petermattis/opttoy/18#-Kz1HuG7y2jwC53PFqwL:-Kz1HuG7y2jwC53PFqwM:bx9gb71) ([raw file](https://github.com/petermattis/opttoy/blob/e2fff1ceedd5f3ecd6f81d2a61fb4ac41c637297/v3/memo.go#L276)):*
> ```Go
> // advance returns the next cursor expression that matches the pattern.
> // The cursor must have been obtained from a previous call to bind() or
> // advance().
> ```

Nit: blank line below this line.

---

*[v3/memo.go, line 280 at r1](https://reviewable.io:443/reviews/petermattis/opttoy/18#-Kz1HzqKRUAI-ILU3wPP:-Kz1HzqKRUAI-ILU3wPQ:bj2dy8r) ([raw file](https://github.com/petermattis/opttoy/blob/e2fff1ceedd5f3ecd6f81d2a61fb4ac41c637297/v3/memo.go#L280)):*
> ```Go
> func (m *memo) advance(e *memoExpr, pattern, cursor *expr) *expr {
> 	if e.loc != cursor.loc {
> 		fatalf("invalid bind expr: %s != %s", e.loc, cursor.loc)
> ```

`s/bind expr/cursor/g`?

---

*[v3/memo.go, line 309 at r1](https://reviewable.io:443/reviews/petermattis/opttoy/18#-Kz1IBjCmkGSrJN35Eo9:-Kz1IBjCmkGSrJN35EoA:b-kypb3r) ([raw file](https://github.com/petermattis/opttoy/blob/e2fff1ceedd5f3ecd6f81d2a61fb4ac41c637297/v3/memo.go#L309)):*
> ```Go
> 	//
> 	// This is somewhat analogous to incrementing an integer (children are digits,
> 	// in reverse order).
> ```

This is the comment I wish I had when understanding how this worked.

---

*[v3/memo.go, line 332 at r1](https://reviewable.io:443/reviews/petermattis/opttoy/18#-Kz1IMIZqu5ta_8wd8OR:-Kz1IMIZqu5ta_8wd8OS:b-snoqmu) ([raw file](https://github.com/petermattis/opttoy/blob/e2fff1ceedd5f3ecd6f81d2a61fb4ac41c637297/v3/memo.go#L332)):*
> ```Go
> }
> 
> // bindGroup is similar to bind, except that it can bind any expression routed
> ```

`s/routed/rooted/g`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/petermattis/opttoy/18#-:-Kz1IhSAJT4mj1vgnPTK:b-57sb40)*

**Comment by RaduBerinde** [comment]
*[v3/memo.go, line 309 at r1](https://reviewable.io:443/reviews/petermattis/opttoy/18#-Kz1IBjCmkGSrJN35Eo9:-Kz1M478xvbuNGgZlY1b:b-itznlb) ([raw file](https://github.com/petermattis/opttoy/blob/e2fff1ceedd5f3ecd6f81d2a61fb4ac41c637297/v3/memo.go#L309)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This is the comment I wish I had when understanding how this worked.
</blockquote></details>

I take it that this code is modeled after existing code? Is it from Orca (https://github.com/greenplum-db/gporca/blob/master/libgpopt/src/search/CBinding.cpp)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/petermattis/opttoy/18)*

**Comment by petermattis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 6 unresolved discussions.

---

*[v3/memo.go, line 309 at r1](https://reviewable.io:443/reviews/petermattis/opttoy/18#-Kz1IBjCmkGSrJN35Eo9:-Kz1NATGXDt2fKd6LQ_u:b-kntddc) ([raw file](https://github.com/petermattis/opttoy/blob/e2fff1ceedd5f3ecd6f81d2a61fb4ac41c637297/v3/memo.go#L309)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I take it that this code is modeled after existing code? Is it from Orca (https://github.com/greenplum-db/gporca/blob/master/libgpopt/src/search/CBinding.cpp)?
</blockquote></details>

It started based on a description from Alberto that I tried to implement, then I took inspiration from Orca. Sort of a blend of both. And now it has your mark.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/petermattis/opttoy/18)*

**Comment by RaduBerinde** [comment]
Updated. I'm also thinking we should rename `memoExpr.match` because it suggests that it matches an expression with the entire pattern but it just matches the root. Perhaps `matchRoot` or `matchPatternRoot`?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/petermattis/opttoy/18#-:-Kz1RI00oQcqgozRV2Fh:bj6mtqc)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 2 files reviewed at latest revision, 6 unresolved discussions.

---

*[v3/memo.go, line 221 at r1](https://reviewable.io:443/reviews/petermattis/opttoy/18#-Kz1HRi2sCo5gdDpGbuZ:-Kz1PW6iYUC2Xz2lhSgj:b-896fix) ([raw file](https://github.com/petermattis/opttoy/blob/e2fff1ceedd5f3ecd6f81d2a61fb4ac41c637297/v3/memo.go#L221)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This probably belongs in `pattern.go`.
</blockquote></details>

Done.

---

*[v3/memo.go, line 251 at r1](https://reviewable.io:443/reviews/petermattis/opttoy/18#-Kz1H_EMHQNHtnR08cDf:-Kz1QLpDU_rr6Re6Cgj8:b-m5n60l) ([raw file](https://github.com/petermattis/opttoy/blob/e2fff1ceedd5f3ecd6f81d2a61fb4ac41c637297/v3/memo.go#L251)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I recall having to initialize `cursor.children` for `pattern leaf` at some point. Seems like that is no longer necessary if the tests are all still passing.
</blockquote></details>

Ah. The tests pass but I noticed something earlier - if I tried do `Printf("%v", cursor)` in the search loop, it would print out a "slice out of bounds" panic. I tried initializing the children in all cases and things print out fine now.

---

*[v3/memo.go, line 276 at r1](https://reviewable.io:443/reviews/petermattis/opttoy/18#-Kz1HuG7y2jwC53PFqwL:-Kz1QiyegUtJEUsBhxIW:b-896fix) ([raw file](https://github.com/petermattis/opttoy/blob/e2fff1ceedd5f3ecd6f81d2a61fb4ac41c637297/v3/memo.go#L276)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Nit: blank line below this line.
</blockquote></details>

Done.

---

*[v3/memo.go, line 280 at r1](https://reviewable.io:443/reviews/petermattis/opttoy/18#-Kz1HzqKRUAI-ILU3wPP:-Kz1R6NnxFScSC2__WMF:b-896fix) ([raw file](https://github.com/petermattis/opttoy/blob/e2fff1ceedd5f3ecd6f81d2a61fb4ac41c637297/v3/memo.go#L280)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`s/bind expr/cursor/g`?
</blockquote></details>

Done.

---

*[v3/memo.go, line 332 at r1](https://reviewable.io:443/reviews/petermattis/opttoy/18#-Kz1IMIZqu5ta_8wd8OR:-Kz1RHTbQGuq7HBKmGGZ:b-896fix) ([raw file](https://github.com/petermattis/opttoy/blob/e2fff1ceedd5f3ecd6f81d2a61fb4ac41c637297/v3/memo.go#L332)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`s/routed/rooted/g`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/petermattis/opttoy/18)*

**Comment by petermattis** [comment]
Either name is fine. Or `shallowMatch` or `matchOp`.

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[v3/memo.go, line 251 at r1](https://reviewable.io:443/reviews/petermattis/opttoy/18#-Kz1H_EMHQNHtnR08cDf:-Kz1Re7A72c_vvCwYXof:bqt6diz) ([raw file](https://github.com/petermattis/opttoy/blob/e2fff1ceedd5f3ecd6f81d2a61fb4ac41c637297/v3/memo.go#L251)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Ah. The tests pass but I noticed something earlier - if I tried do `Printf("%v", cursor)` in the search loop, it would print out a "slice out of bounds" panic. I tried initializing the children in all cases and things print out fine now.
</blockquote></details>

Ah, that was it. Operators expect their expressions have the children described by their `exprLayout`. So a join expression always has `len(expr.children) == 3`. I think this is a good invariant to keep.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/petermattis/opttoy/18#-:-Kz1S0rKOPk6yrRD7L-g:b-w9xl9i)*

**Comment by RaduBerinde** [comment]
I like `matchOp`, updated.

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/petermattis/opttoy/18#-:-Kz1TQ2Z0PknVm02QUOk:bw4jcdw)*

**Pull request merged**
